//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSIGE_ResguardoEntities : DbContext
    {
        public DSIGE_ResguardoEntities()
            : base("name=DSIGE_ResguardoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Aceesos_Evento> tbl_Aceesos_Evento { get; set; }
        public virtual DbSet<tbl_Cargo_Personal> tbl_Cargo_Personal { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<tbl_Distritos> tbl_Distritos { get; set; }
        public virtual DbSet<tbl_Empresas> tbl_Empresas { get; set; }
        public virtual DbSet<tbl_Estados> tbl_Estados { get; set; }
        public virtual DbSet<tbl_GrupoTabla_Cab> tbl_GrupoTabla_Cab { get; set; }
        public virtual DbSet<tbl_GrupoTabla_Det> tbl_GrupoTabla_Det { get; set; }
        public virtual DbSet<TBL_Operarios_RegistroGPS> TBL_Operarios_RegistroGPS { get; set; }
        public virtual DbSet<tbl_Parametro_Movil> tbl_Parametro_Movil { get; set; }
        public virtual DbSet<tbl_ParteDiario_Cab> tbl_ParteDiario_Cab { get; set; }
        public virtual DbSet<tbl_Perfil> tbl_Perfil { get; set; }
        public virtual DbSet<tbl_Perfil_Accesos> tbl_Perfil_Accesos { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
        public virtual DbSet<tbl_Servicios> tbl_Servicios { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
    }
}
