//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Solicitud_Cab
    {
        public int id_Solicitud_Cab { get; set; }
        public Nullable<System.DateTime> fechaAtencion { get; set; }
        public Nullable<int> id_Servicios { get; set; }
        public Nullable<int> id_PersonalCoordinar { get; set; }
        public Nullable<int> asigna_JC { get; set; }
        public Nullable<int> id_PersonalJefeCuadrilla { get; set; }
        public Nullable<int> cantidadEfectivos { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
        public Nullable<double> cantidadHoras { get; set; }
        public Nullable<System.DateTime> fechaAsignacion_Final { get; set; }
    }
}
